/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function setEfficiency(pid: number, value: boolean): void;

export declare function getEfficiency(pid: number): boolean;

export declare function protocolInject(path: string): void;

export declare function sleeper(value: boolean): void;
