[package]
name = "efficiency"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
windows = { version = "0.56", features = [ "Win32_System_Threading" ] }
napi = "2"
napi-derive = "2"

[build-dependencies]
napi-build = "1"