[package]
name = "sc-rename"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]

[profile.release]
lto = true
opt-level = "s"
debug = false
panic = "abort"
strip = "symbols"
codegen-units = 1